/*
 * File: app/view/persons/Grid.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.persons.Grid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.personsgrid',

    height: 250,
    width: 400,
    title: 'Edit Records',
    store: 'Persons',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'firstName',
                    text: 'First Name',
                    flex: 1,
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'lastName',
                    text: 'Last Name',
                    flex: 1,
                    editor: {
                        xtype: 'textfield'
                    }
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {
                    pluginId: 'personsGridEditor'
                })
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnAdd',
                            text: 'Add Record'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDel',
                            text: 'Delete Record'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});