/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FriendsWithBeer.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'FriendsWithBeer.view.Introduction',
        'FriendsWithBeer.view.friendinfo'
    ],

    config: {
        items: [
            {
                xtype: 'intro',
                title: 'About',
                iconCls: 'info'
            },
            {
                xtype: 'friendinfo',
                title: 'Friends',
                iconCls: 'user_list'
            },
            {
                xtype: 'list',
                title: 'Beers',
                iconCls: 'info',
                itemTpl: [
                    '<div>',
                    '    {id}',
                    '    {name} {type} <br />',
                    '    {country}',
                    '</div>'
                ],
                store: 'Beers',
                grouped: true,
                onItemDisclosure: true
            }
        ],
        tabBar: {
            docked: 'bottom',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        }
    }

});