/*
 * File: app/view/main.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FriendsWithBeer.view.main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'FriendsWithBeer.view.Introduction'
    ],

    config: {
        layout: {
            animation: 'slide',
            type: 'card'
        },
        items: [
            {
                xtype: 'intro',
                title: 'About',
                iconCls: 'info'
            },
            {
                xtype: 'container',
                title: 'Tab 2',
                iconCls: 'info'
            },
            {
                xtype: 'container',
                title: 'Tab 3',
                iconCls: 'info'
            }
        ],
        tabBar: {
            docked: 'bottom',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        }
    }

});