/*
 * File: app/store/Locations.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FriendsWithBeer.store.Locations', {
    extend: 'Ext.data.Store',
    alias: 'store.Locations',

    requires: [
        'FriendsWithBeer.model.Location'
    ],

    config: {
        autoLoad: true,
        model: 'FriendsWithBeer.model.Location',
        storeId: 'Locations',
        sorters: [
            {
                property: 'idlocation'
            },
            {
                property: 'title'
            },
            {
                property: 'description'
            }
        ],
        grouper: {
            groupFn: function(item) {
                return item.get('title');
            }
        }
    }
});