/*
 * File: app/controller/Persons.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Persons', {
    extend: 'Ext.app.Controller',

    models: [
        'Person'
    ],
    stores: [
        'Persons'
    ],

    refs: [
        {
            ref: 'personsGrid',
            selector: 'personsgrid'
        }
    ],

    onBtnAddClick: function(button, e, options) {
        var grid = this.getPersonsGrid();
        var plugin = grid.getPlugin('personsGridEditor');
        plugin.cancelEdit();

        var rec = Ext.create('MyApp.model.Person', {
            firstName: '', 
            lastName: ''
        });
        Ext.getStore('Persons').insert(0,rec);
        plugin.startEdit(0,0);


    },

    onBtnDelClick: function(button, e, options) {
        var grid = this.getPersonsGrid();
        var plugin = grid.getPlugin('personsGridEditor');
        var store = grid.getStore();
        var sm = grid.getSelectionModel();

        plugin.cancelEdit();
        store.remove(sm.getSelection());
        if (store.getCount() > 0) {
            sm.select(0);
        }
    },

    init: function(application) {
        this.control({
            "personsgrid #btnAdd": {
                click: this.onBtnAddClick
            },
            "#btnDel": {
                click: this.onBtnDelClick
            }
        });
    }

});
