/*
 * File: app/view/Earmarks.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SpendingPortal.view.Earmarks', {
    extend: 'Ext.window.Window',
    alias: 'widget.earmarks',

    autoShow: true,
    height: 250,
    width: 500,
    constrain: true,
    layout: {
        type: 'border'
    },
    closable: false,
    title: 'Please Select Sponsor(s)',
    maximizable: true,
    minimizable: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    itemId: 'earmarkGrid',
                    frameHeader: false,
                    columnLines: true,
                    store: 'Earmarks',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 50,
                            dataIndex: 'ENACTED_YEAR',
                            text: 'Year',
                            format: '0000'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'AGENCY_TITLE',
                            text: 'Agency',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'BUREAU_TITLE',
                            text: 'Bureau',
                            flex: 1
                        },
                        {
                            xtype: 'templatecolumn',
                            tpl: [
                                '{[Ext.util.Format.usMoney(values.AMT_CONF * 1000)]}'
                            ],
                            width: 100,
                            align: 'right',
                            dataIndex: 'bool',
                            text: 'Amt'
                        }
                    ],
                    features: [
                        {
                            ftype: 'grouping',
                            groupHeaderTpl: [
                                'Sponsor: {name}'
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});