/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({

    requires: [
        'Ext.window.MessageBox'
    ],
    views: [
        'Main'
    ],
    autoCreateViewport: true,
    controllers: [
        'Main',
        'Sponsors',
        'Earmarks'
    ],
    name: 'SpendingPortal',

    launch: function() {


        Ext.ComponentQuery.query('#centerpanel')[0].add(
        { xtype: 'sponsors', x:5, y:20},
        { xtype: 'earmarksviewer', x: 500, y: 20},
        { xtype: 'sponsorchart', x:500, y: 300}
        );
    }

});
