/*
 * File: app/view/Sponsors.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SpendingPortal.view.Sponsors', {
    extend: 'Ext.window.Window',
    alias: 'widget.sponsors',

    autoShow: true,
    height: 600,
    width: 472,
    constrain: true,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: 'Congressional Representatives',
    maximizable: true,
    minimizable: true,

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});